# LSI (Latent Semantic Indexing) Keywords
lsi: false

# Enable safe mode
safe: true

# Site Settings
logo: /book/images/media/ARMTEC Logo Medium+.png
title: [Move Forward with...]
description: [This is Our Technical Support Division]
baseurl: /ARMTEC

# Build Settings
markdown: kramdown
# theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal
plugins:
  - jekyll-target-blank


# Whitelist plugins under safe mode.
# Note that if `some-other-jekyll-plugin` is not listed here it will not be loaded under safe mode.
whitelist:
  - jekyll-target-blank
