# LSI (Latent Semantic Indexing) Keywords
lsi: false

# Enable safe mode
safe: true

# Site Settings
logo: /book/images/media/ARMTEC Logo Medium+.png
title: [Your path to success...]
email: emofsnead@gmail.com
description: [This is Our Technical Support Division]
baseurl: ""
url: https://rightsandwrongsgit.github.io

# site-css:
#   - "/assets/css/custom-styles.css"

# Build Settings
markdown: kramdown
# theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme


# Whitelist plugins under safe mode.
# Note that if `some-other-jekyll-plugin` is not listed here it will not be loaded under safe mode.
whitelist:
  - jekyll-target-theme
