# LSI (Latent Semantic Indexing) Keywords
lsi: false

# Enable safe mode (true or false)
safe: true

# Standard stuff from https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll
# source: [your repo's top level directory]
# incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge



# Site Settings
logo: /book/images/media/ARMTEC Logo Medium+.png
title: [Your path to success...]
email: emofsnead@gmail.com
description: [Providing the tools you need]
# baseurl: ""
baseurl: "/ARMTEC"
url: https://rightsandwrongsgit.github.io
# repository: RightsandWrongsgit/ARMTEC


# Build Settings
markdown: kramdown
# theme: minimal@v0.2.0
# theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/minimal
# plugins:
#  - jekyll-remote-theme


# Whitelist plugins under safe mode.
# Note that if `some-other-jekyll-plugin` is not listed here it will not be loaded under safe mode.
whitelist:
  - jekyll-target-theme


# Include settings
# include: 
# - "_includes/*"
# - "_layouts/*"
# - "_data/*"
# - "img/*"



